---
cli:
  bootstrap: bootstrap.php
schema:
  auto_id: true
  finders:
  - Phifty::Schema::Finder::AppSchemaFinder
seeds:
databases:
  master:
    driver: mysql
    host: localhost
    database: testing
    user: root
    pass:
